export const TOOLS = [
  "Adobe After Effects",
  "Adobe Audition",
  "Adobe Dreamweaver",
  "Adobe Illustrator",
  "Adobe InDesign",
  "Adobe Lightroom",
  "Adobe Photoshop",
  "Adobe Premiere Pro",
  "Adobe XD",
  "Affinity Designer",
  "Affinity Photo",
  "Anima",
  "Anker",
  "Arduino",
  "Audacity",
  "BandLab",
  "Blender",
  "BricsCAD",
  "Canva",
  "Cinema 4D",
  "Clip Studio Paint",
  "Clipchamp",
  "DALL-E",
  "DaVinci Resolve",
  "Figma",
  "Filmora",
  "Final Cut Pro",
  "Framer",
  "GarageBand",
  "GIMP",
  "GitHub",
  "Google SketchUp",
  "Houdini",
  "Inkscape",
  "KeyShot",
  "Krita",
  "LibreOffice Impress",
  "LightWave 3D",
  "Logic Pro",
  "Looka",
  "Luminar",
  "Marvelous Designer",
  "Maya",
  "Midjourney",
  "Miro",
  "MS PowerPoint",
  "Notion",
  "OBS Studio",
  "Octane Render",
  "Procreate",
  "PTGui",
  "Renoise",
  "Rhino 3D",
  "Sai",
  "Shotcut",
  "SolidWorks",
  "Sony Vegas Pro",
  "Spline",
  "Stable Diffusion",
  "Substance 3D Painter",
  "Tinkercad",
  "TouchDesigner",
  "Trello",
  "Unreal Engine",
  "V-Ray",
  "Wix",
  "WordPress",
  "ZBrush",
] as const;
